# Generated by Django 5.2.1 on 2025-08-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_subservice_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='file_path',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
