# Generated by Django 5.2.1 on 2025-08-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
