# Generated by Django 5.2.1 on 2025-09-13 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='duration',
            field=models.IntegerField(help_text='Time Duration in hours'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.service')),
            ],
        ),
    ]
